### ISSUE TITLE
Idea: help menu cacti

### ISSUE THREAD

**Issue by ThatOneCalculator** [willeccles/cpm#14]
Do you think it would be a good idea to replace the help menu arrows (`->`) with the cactus emoji? Might be fun.

```
~ cpm h
cpm [i|r|l|C|u|U|s|S|I|c|h] [pkg]...
🌵 i | install install one or more packages
🌵 r | remove  remove one or more packages
🌵 l | list    list installed packages
🌵 C | count   count installed packages
🌵 u | update  update package lists
🌵 U | upgrade upgrade all packages
🌵 s | search  search for a package
🌵 S | show    show information about a package
🌵 I | info    same as show
🌵 c | clean   clean up leftover files/caches/orphans
🌵 h | help    show this message
```

**Comment by willeccles** [comment]
This won't render properly if the user doesn't have emoji support in their terminal or font(s). It also renders oddly in general because they're double-width characters. I think sticking with the current implementation would be wise.

**Comment by ThatOneCalculator** [comment]
I get that. It looks fairly nice in alacritty, but some other terms I could understand having issues.
