### ISSUE TITLE
Support more package manager features

### ISSUE THREAD

**Issue by 6gk** [willeccles/cpm#17]
Some useful ones I use and always forget

 - List files in package
   * **Debian:** `dpkg -L <pkg>`
   * **Arch:** `pacman -Ql <pkg>`
 - Show package which owns a file
   * **Debian:** `dpkg -S /path/to/file`
   * **Arch:** `pacman -Qo /path/to/file`

**Comment by willeccles** [comment]
bruh

**Comment by willeccles** [comment]
I forgot this was a thing. You can go ahead and implement something like that, not a big deal. Just do the research and add the ones you can. If you can't find some of them just make that known, I think there's somewhere in like CONTRIBUTING.md or something that tells you what message to write when something is not supported.

**Comment by 6gk** [comment]
Alright.

I forgot I made this issue too. I'll look into it later.

**Comment by 6gk** [comment]
I did my research, I'll implement it later. (Maybe tomorrow? idk)

```
listing files in package
ARCH: pacman -Ql       [pkgname]
APK:  apk info -L      [pkgname]
DEB:  dpkg -L          [pkgname]
DNF:  dnf repoquery -l [pkgname]
EMRG: equery files     [pkgname]
MPRT: port contents    [pkgname]
VOID: xbps-query -f    [pkgname]
NIX:  unsupported

showing what package owns a file:
ARCH: pacman -Qo          /path/to/file
APK:  apk info --who-owns /path/to/file
DEB:  dpkg -S             /path/to/file
DNF:  dnf provides       [/path/to/]file (also lists non-installed pkgs)
EMRG: equery belongs      /path/to/file  (qfile too?)
MPRT: port provides       /path/to/file
VOID: xbps-query -o       /path/to/file
NIX:  unsupported (& practically useless)
```

**Comment by willeccles** [comment]
> I'd like to know what short/long arguments you'd use for these, too.

Use `f` or `files`.

**Comment by 6gk** [comment]
(there are 2 different commands there)

**Comment by willeccles** [comment]
What if you make this one command, with different args? Something like this:

```sh
if [ -f "$1" ]; then
    # who owns the file
else
    # list files in package
fi
```

**Comment by 6gk** [comment]
That's a decent idea, I'll keep it in mind.

**Comment by willeccles** [comment]
Lovely weather out there right now.

**Comment by 6gk** [comment]
😭 dont pick on me

[image: image.png]

**Comment by 6gk** [comment]
well that didn't work.

![image](https://user-images.githubusercontent.com/40295114/109212715-9e398b00-77fb-11eb-8ec1-a42f75025bff.png)

**Comment by willeccles** [comment]
Make it happen

**Comment by 6gk** [comment]
Is that a threat?
