### ISSUE TITLE
apk is using the wrong operator for the count function.

### ISSUE THREAD

**Issue by foxsouns** [willeccles/cpm#23]
apk has tot setup wrong. It's using `apk -vv info || tot;;`, which includes `||`, the OR operator, when it should be `|`, the pipe operator. I would do this myself, and probably will, but the current PR is supposed to drop soon and I don't want to cause any complications.

(Also: why is Adélie listed in the comments of cpm, but not on the README next to Alpine? lol)

**Comment by foxsouns** [comment]
[Here](https://github.com/foxsouns/cpm/tree/fix-alpine) is my branch for fixing this, I'll try and update it when the new PR comes in, and put it in when it's ready.

**Comment by willeccles** [comment]
You can just open a PR for this now.
