### ISSUE TITLE
missing implimentation for slack's "files" (#27)

### ISSUE THREAD

**Issue by foxsouns** [willeccles/cpm#28]
Slackware needs a proper implementation of files. This is being worked on in pull request #44. Assuming everything looks good, this issue should be resolved soon.

**Comment by foxsouns** [comment]
if i'm overcomplicating this, and there's an easy way to do this, please tell me

**Comment by 6gk** [comment]
Ahh, I see.

Unless there will be leading whitespace, you shouldn't need to specify
`IFS= `

```
stopslacking() {
  unset files
  while read -r line; do
    [ "$line" = "FILE LIST:" ] && files=1
    [ "$files" ] && printf "%s\n" "$line"
  done
}
```

Would probably work if you want to use a single loop, however due to the
test it will be mildly slower so ehhh
(the speed differences are literally irrelevant on anything but an intel
4004 but ehhhh)

**Comment by willeccles** [comment]
Something like this might work:
```sh
slacklist() {
  pkginfo="/var/whatever/$1"
  if [ -f "$pkginfo" ];
    found=
    while IFS= read -r line; do
      [ "$line" = "FILE LIST:" ] && found=yes
      [ -n "$found" ] && printf "%s\n" "$line"
    done <"$pkginfo"
  else
    # error handling
  fi
}
```
Call it as `slacklist zsh`, for example.

**Comment by foxsouns** [comment]
also, that var directory is `/var/log/packages/PACKAGE`
