### ISSUE TITLE
Installation instructions are unnecessary

### ISSUE THREAD

**Issue by sophec** [willeccles/cpm#41]
At the very least they ought to be simplified/generalized. At worst, just remove them.

**Comment by foxsouns** [comment]
@gk one could tack a `&& sudo chmod 755 /usr/local/bin/cpm` and call it done, technically

**Comment by 6gk** [comment]
@foxsouns True, but at that point it's not really much shorter than it currently is.

**Comment by 6gk** [comment]
1. `-o -` is redundant, outputting to stdout is the default behavior.
2. it won't interpret arguments

**Comment by foxsouns** [comment]
~~that command was 1ms too slow time to reinstall _[insert distro of choice]_~~
