### ISSUE TITLE
prt-get and guix do not use $SUDO?

### ISSUE THREAD

**Issue by willeccles** [willeccles/cpm#56]
I'm not familiar with guix, so this may be appropriate for guix, but prt-get seems like it would require root.

**Comment by foxsouns** [comment]
> And @foxsouns, you added Crux support. Thoughts?

that was an oversight: prt-get should be ran with `$SUDO`.

**Comment by xgqt** [comment]
The case of Guix is similar to Nix, so: ran rootless it manages environment of the user and with root access can modify the whole system.
If I would force the use of `sudo` them `cpm` could not work for the user,
right now it should be able to both manage user with `$ cpm ...` and system with `$ sudo cpm ...`.

**Comment by willeccles** [comment]
> > And @foxsouns, you added Crux support. Thoughts?
> 
> that was an oversight: prt-get should be ran with `$SUDO`.

@foxsouns Could you open a PR to add this as necessary?

**Comment by willeccles** [comment]
> The case of Guix is similar to Nix, so: ran rootless it manages environment of the user and with root access can modify the whole system. If I would force the use of `sudo` them `cpm` could not work for the user, right now it should be able to both manage user with `$ cpm ...` and system with `$ sudo cpm ...`.

Alright, that makes sense. Will leave it off for Guix.
