### ISSUE TITLE
CP/M

### ISSUE THREAD

**Issue by gek169** [willeccles/cpm#68]
There's a naming issue with this project, there is a (most likely trademarked) operating system called CP/M which could potentially conflict with your project.

**Comment by gek169** [comment]
https://en.wikipedia.org/wiki/CP/M

**Comment by foxsouns** [comment]
1. latest release was 40 years ago
2. it's open source now
3. there's a slash in their name
4. their acronym doesn't mean "Cactus Package Manager" so there is no conflict

**Comment by gek169** [comment]
actually, I was initially confused when I saw the project name.

But it it is what it is
